Add server instances.

diff --git a/device-postgresql13-el9/src/main/resources/usr/libexec/device-postgresql-autodiscovery b/device-postgresql13-el9/src/main/resources/usr/libexec/device-postgresql-autodiscovery
--- a/device-postgresql13-el9/src/main/resources/usr/libexec/device-postgresql-autodiscovery
+++ b/device-postgresql13-el9/src/main/resources/usr/libexec/device-postgresql-autodiscovery
@@ -6,21 +6,173 @@
 #
 # This script autogenerates any required postgresql instances.
 
+set -e
+umask 0007
+
 
 #
-# Data directory does not exist, bail out
-if test ! -d "${PGDATA}"; then
-  echo "Data directory does not exist, postgresql configuration skipped."
-  exit 1
-fi
+# Handle the cleanup
+# ------------------
+cleanup_before_exit () {
+  if [ -d "${tmpdir}" ]; then
+    rm -rf "${tmpdir}"
+  fi
+}
+# be in a temporay workspace (this works on linux and macosx)
+tmpdir=`mktemp -d 2>/dev/null || mktemp -d -t 'tmpdir'`
+# trap catches the exit signal and runs the specified function
+trap cleanup_before_exit EXIT
+# be in our directory
+cd "${tmpdir}"
+
 
 #
-# Data directory exists but is empty, we need to initialise
+# Create instance that does not yet exist
+create_instance() {
+  instance="${1}"
 
-if test -n "$(find ${PGDATA} -maxdepth 0 -empty)" ; then
-  /usr/bin/postgresql-setup --initdb
-fi
+  install -o root -g root -m 755 -d "/etc/systemd/system/postgresql@${instance}.service.d"
+
+  cat >> local.conf <<- EOF
+[Service]
+Environment=PGDATA=/var/lib/pgsql/data-${instance}
+EOF
+
+  install -o root -g root -m 644 local.conf "/etc/systemd/system/postgresql@${instance}.service.d"
+
+  systemctl daemon-reload
+
+  postgresql-setup --initdb --unit="postgresql@${instance}" --port 5432
+}
+
 
 #
-# Configure postgresql
+# Remove existing instance
+remove_instance() {
+  instance="${1}"
+
+  rm -f "/etc/systemd/system/postgresql@${instance}.service.d/local.conf"
+  if test -d "/etc/systemd/system/postgresql@${instance}.service.d"; then
+    rmdir "/etc/systemd/system/postgresql@${instance}.service.d"
+  fi
+
+  if test -d "/var/lib/pgsql/data-${instance}"; then
+    mv --backup=numbered -t "/var/lib/pgsql/backups/" "/var/lib/pgsql/data-${instance}"
+  fi
+}
+
+
+#
+# Per application? Run all scripts
+
+run_scripts() {
+
+  instance="${1}"
+  line="${2}"
+
+  logger -t "postgresql-autodiscovery@${instance}" "running autodiscovery for postgresql instance ${instance}..."
+
+  rm -f "${line}/warning"
+
+  find "$0.d" -type f -executable | sort | \
+  while read x; do
+    "$x" "${instance}" "${line}" < /dev/null || touch error;
+  done
+
+  if test ! -f "error"; then
+    logger -t "postgresql-autodiscovery@${instance}" "completed autodiscovery for postgresql instance ${instance}."
+  else
+    logger -t "postgresql-autodiscovery@${instance}" "failed autodiscovery for postgresql instance ${instance}."
+  fi
+
+}
+
+
+#
+# Add/remove postgres instances
+
+find /etc/device/services/db/postgresql/instance/ -mindepth 1 -maxdepth 1 -type l | \
+while read line; do
+
+  target=$(readlink -f "$line")
+
+  if test ! -f "$line/name.txt"; then
+    continue;
+  fi
+  instance="$(head -n 1 $line/name.txt)"
+
+  # remove old instances
+  if test -f "$line/removed"; then
+
+    logger -t postgresql-autodiscovery "removing postgresql server instance ${instance}..."
+
+    systemctl disable "postgresql@${instance}"
+    systemctl stop "postgresql@${instance}"
+
+    remove_instance "${instance}"
+    logger -t postgresql-autodiscovery "removed postgresql server instance ${instance}."
+
+    # remove folder
+    rm -f "${target}"/*
+    rmdir "${target}"
+    rm -f "${line}"
+
+  # add new instances
+  elif test -f "$line/added"; then
+
+    logger -t postgresql-autodiscovery "creating postgresql server instance ${instance}..."
+    create_instance "${instance}"
+    run_scripts "${instance}" "${line}"
+    logger -t postgresql-autodiscovery "created postgresql server instance ${instance}."
+
+    if test -f "$line/disabled.bin"; then
+
+      systemctl disable "postgresql@${instance}"
+      systemctl stop "postgresql@${instance}"
+
+    else
+
+      systemctl enable "postgresql@${instance}"
+      systemctl start "postgresql@${instance}"
+
+    fi
+
+    rm -f "$line/added"
+
+  # update instances
+  elif test -f "$line/updated"; then
+
+    instance="$(head $line/name.txt)"
+
+    if test -f "$line/disabled.bin"; then
+
+      systemctl disable "postgresql@${instance}"
+      systemctl stop "postgresql@${instance}"
+
+      run_scripts "${instance}" "${line}"
+
+    else
+
+      run_scripts "${instance}" "${line}"
+
+      systemctl enable "postgresql@${instance}"
+      systemctl start "postgresql@${instance}"
+
+    fi
+
+    rm -f "$line/updated"
+
+  # something we depend on changed
+  else
+
+    instance="$(head $line/name.txt)"
+
+    run_scripts "${instance}" "${line}"
+
+    systemctl try-reload-or-restart "postgresql@${instance}"
+
+  fi
+
+done
+
 
diff --git a/device-postgresql13-el9/src/main/resources/usr/libexec/device-postgresql-postdiscovery b/device-postgresql13-el9/src/main/resources/usr/libexec/device-postgresql-postdiscovery
--- a/device-postgresql13-el9/src/main/resources/usr/libexec/device-postgresql-postdiscovery
+++ b/device-postgresql13-el9/src/main/resources/usr/libexec/device-postgresql-postdiscovery
@@ -27,6 +27,16 @@ cd /tmp
 find /etc/device/services/db/postgresql/database/ -mindepth 1 -maxdepth 1 -type l | \
 while read line; do
 
+  if test ! -f "$line/instance.d/name.txt" -o ! -f "$line/instance.d/port.txt"; then
+    continue;
+  fi
+  if test ! -f "$line/name.txt"; then
+    continue;
+  fi
+
+  instance="$(head -n 1 $line/instance.d/name.txt)"
+  port="$(head -n 1 $line/instance.d/port.txt)"
+
   # add new databases
   if test -f "$line/added"; then
 
@@ -43,13 +53,13 @@ while read line; do
 
     # add local user if needed
     role="$(head $line/local-owner.txt)"
-    echo "DO \$\$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${role}') THEN CREATE ROLE ${role} WITH LOGIN CREATEDB; END IF; END \$\$;" | runuser -u postgres -- /usr/bin/psql  > /dev/null 2>&1
+    echo "DO \$\$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${role}') THEN CREATE ROLE ${role} WITH LOGIN CREATEDB; END IF; END \$\$;" | runuser -u postgres -- /usr/bin/psql --port=${port}  > /dev/null 2>&1
 
     # database already exist? mark as an error and do nothing
-    runuser -u postgres -- /usr/bin/psql -tc "SELECT 1 FROM pg_database WHERE datname = '${name}'" | grep -q 1 && echo "Database already exists" > "$line/error" && rm -f "$line/added" && exit 1
+    runuser -u postgres -- /usr/bin/psql --port=${port} -tc "SELECT 1 FROM pg_database WHERE datname = '${name}'" | grep -q 1 && echo "Database already exists" > "$line/error" && rm -f "$line/added" && exit 1
 
     # add database
-    runuser -u postgres -- /usr/bin/createdb --owner="${role}" --locale="${locale}" --encoding="${encoding}" --template=template0 "${database}"
+    runuser -u postgres -- /usr/bin/createdb --port=${port} --owner="${role}" --locale="${locale}" --encoding="${encoding}" --template=template0 "${database}"
 
     rm -f "$line/added"
   fi
@@ -61,7 +71,7 @@ while read line; do
 
     # remove database, but only if no error was created making the database
     if test ! -f "$line/error"; then
-      runuser -u postgres -- /usr/bin/dropdb "${database}"
+      runuser -u postgres -- /usr/bin/dropdb --port=${port} "${database}"
     fi
 
     # remove folder
